### PR TITLE
Ros2 v0.8.0 scenario entities

### PR DESCRIPTION
**Pull request by k0suke-murakami**
depends on #56

### CODE REVIEW

**Comment by tkimura4** [comment]
Did you forget this PR?
 https://github.com/tier4/AutowareT4BScenario/commit/52c286a9a8a9e5f2bdac6097d022882ba68975e3#diff-bddeed3f04d658da088557f51b4ae73acf618ac82333acc1763d9ec37b694b9a

**Comment by k0suke-murakami** [comment]
https://github.com/tier4/autoware.proj/blob/v0.5.0/autoware.proj.repos#L52
https://github.com/tier4/autoware.proj/blob/v0.8.0/autoware.proj.repos#L52

I referenced `f654a97..3c71d95`(v0.5 to v0.8), seems like `52c286a9a` is after v0.8.
I would like to add the commit for v0.9 upgrade or did I miss anything...?

**Comment by tkimura4** [comment]
Sorry, my mistake!

**Comment by tkimura4** [comment]
LGTM!

**Pull request merged**
