### PR TITLE
Enable lints in scenario_api

### PR DESCRIPTION
**Pull request by nnmm**
Clang-tidy pointed out an unused parameter in `isNpcExist()`. I checked and deleted the function altogether since it is never used in the codebase.

### CODE REVIEW

**Review by esteve — APPROVED** [review]

**Comment by nnmm** [comment]
I can't figure out why the build is failing ... npc_simulator tests are passing for me, and the line it complains about doesn't even have a comment.

**Comment by jilaada** [comment]
> I can't figure out why the build is failing ... npc_simulator tests are passing for me, and the line it complains about doesn't even have a comment.

I made the fix to `npc_simulator` [here](https://github.com/tier4/planning_simulator.iv.universe/pull/17). Hopefully after this PR is merged, these builds will be fixed.

**Comment by esteve** [comment]
Triggered CI to pick up @jilaada 's fix, will merge once CI passes.

**Comment by nnmm** [comment]
Thanks to both of you!

**Pull request merged**
